nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
